export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'

export const FETCH_FEED_START = 'FETCH_FEED_START'
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS'
export const FETCH_FEED_FAILURE = 'FETCH_FEED_FAILURE'

export const FETCH_LOAD_MORE_FEED_START = 'FETCH_LOAD_MORE_FEED_START'
export const FETCH_LOAD_MORE_FEED_SUCCESS = 'FETCH_LOAD_MORE_FEED_SUCCESS'
export const FETCH_LOAD_MORE_FEED_FAILURE = 'FETCH_LOAD_MORE_FEED_FAILURE'